name: on-tag-push-to-main

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project at Full Depth
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Run Release
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
